export type Treatment = {
  slug: string;
  title: string;
  image: string;
  summary: string;
  overview: string;
  suitableFor: string[];
  process: string[];
  aftercare: string[];
  benefits: string[];
  appointment: string;
  recovery: string;
  maintenance: string;
};

export const TREATMENTS: Treatment[] = [
  {
    slug: "aesthetic-composite-fillings",
    title: "Aesthetic Composite Fillings",
    image: "/img/service-aesthetic-composite.jpg",
    summary: "Tooth-coloured restorations designed to repair front teeth with a natural appearance.",
    overview: "Composite resin is carefully shaped and polished to restore damaged tooth structure while respecting the natural colour, contour and character of your smile.",
    suitableFor: ["Small chips or fractures", "Worn or uneven edges", "Visible cavities or discolouration"],
    process: ["Dental assessment and shade selection", "Conservative preparation and layered composite placement", "Finishing, polishing and bite review"],
    aftercare: ["Maintain daily brushing and flossing", "Attend routine reviews so the restoration can be checked"],
    benefits: ["Conserves more natural tooth structure than many indirect restorations", "Colour and contour can be refined to blend with nearby teeth", "Often completed in a single clinical visit"],
    appointment: "The tooth is isolated, gently prepared and restored in thin composite layers. Each layer is shaped before the final surface is polished and the bite is checked.",
    recovery: "Most patients return to normal activities immediately. Mild short-term sensitivity can occur, especially if the repaired area was close to the inner tooth.",
    maintenance: "With good home care and regular reviews, composite restorations can serve well for years. Their lifespan varies with bite forces, habits and the size of the repair.",
  },
  {
    slug: "front-tooth-restorations",
    title: "Front Tooth Restorations",
    image: "/img/service-front-tooth-restoration.jpg",
    summary: "Detail-focused composite treatment for chipped, worn or uneven front teeth.",
    overview: "Front-tooth restoration focuses on rebuilding shape and symmetry with a conservative approach tailored to the tooth and the surrounding smile.",
    suitableFor: ["Chipped front teeth", "Uneven tooth edges", "Minor shape or spacing concerns"],
    process: ["Smile and bite assessment", "Shape, colour and proportion planning", "Layered restoration followed by detailed polishing"],
    aftercare: ["Avoid biting very hard objects with restored teeth", "Schedule a review if the bite feels different"],
    benefits: ["Restores a smoother, more balanced front-tooth outline", "Uses a conservative approach tailored to the damaged area", "Shade, texture and light reflection are planned together"],
    appointment: "After photographs and shade selection, the damaged area is prepared conservatively. Composite is layered, sculpted and polished while tooth contacts and bite are reviewed.",
    recovery: "There is usually little or no downtime. The restored tooth may feel slightly different at first while the lips and tongue adjust to its new contour.",
    maintenance: "Protect the front teeth from pens, ice and other hard objects. Reviews allow small surface changes or polish to be addressed early.",
  },
  {
    slug: "natural-smile-repair",
    title: "Natural Smile Repair",
    image: "/img/service-natural-smile-repair.jpg",
    summary: "Conservative composite care planned to blend with surrounding teeth.",
    overview: "Natural smile repair aims to preserve healthy tooth tissue while restoring small defects with colour, translucency and contours that blend into the smile.",
    suitableFor: ["Minor chips and wear", "Small localised defects", "Patients seeking conservative improvement"],
    process: ["Detailed clinical assessment", "Minimal preparation where appropriate", "Layering, contouring and final polish"],
    aftercare: ["Use a soft toothbrush and non-abrasive toothpaste", "Protect the teeth from habits such as nail biting"],
    benefits: ["Preserves healthy enamel wherever clinically possible", "Repairs local defects without changing the whole smile", "Builds natural-looking translucency and surface detail"],
    appointment: "The dentist studies the smile from several angles, selects matching materials and restores only the areas that need support. Final shaping is checked during smiling and speech.",
    recovery: "Normal daily activity can usually continue straight away. Any temporary sensitivity or awareness of the restored area should gradually settle.",
    maintenance: "Gentle cleaning, routine examinations and avoiding damaging habits help preserve the repair and surrounding natural teeth.",
  },
  {
    slug: "composite-shade-matching",
    title: "Composite Shade Matching",
    image: "/img/service-shade-matching.jpg",
    summary: "Careful colour and contour selection for harmonious restorations.",
    overview: "Shade matching considers hue, brightness, translucency and surface texture so a composite restoration sits naturally beside neighbouring teeth.",
    suitableFor: ["Visible front-tooth restorations", "Replacing mismatched composite", "Aesthetic repair planning"],
    process: ["Shade assessment in appropriate lighting", "Selection and testing of composite shades", "Layering and polishing to refine the match"],
    aftercare: ["Limit staining food and drinks during the first day", "Keep regular cleaning and review appointments"],
    benefits: ["Improves harmony between a restoration and adjacent teeth", "Accounts for translucency rather than colour alone", "Refines both surface texture and final polish"],
    appointment: "Shade is assessed before the tooth becomes dehydrated. Different composite opacities may be tested and layered, then viewed under more than one lighting condition.",
    recovery: "No special recovery period is normally required. The final appearance is best judged after the tooth has rehydrated and the surrounding tissues have settled.",
    maintenance: "Composite can collect surface stain over time. Professional polishing and review can help maintain the match without automatically replacing the restoration.",
  },
  {
    slug: "teeth-cleaning",
    title: "Teeth Cleaning",
    image: "/img/service-teeth-cleaning.jpg",
    summary: "Professional cleaning focused on removing deposits and refreshing the smile.",
    overview: "Professional cleaning removes plaque, calculus and surface stains that daily brushing may not reach, while supporting healthier gums and fresher breath.",
    suitableFor: ["Plaque or calculus buildup", "Surface staining", "Routine preventive dental care"],
    process: ["Gum and deposit assessment", "Careful professional scaling", "Polishing and personalised hygiene guidance"],
    aftercare: ["Follow the recommended brushing and flossing routine", "Temporary sensitivity usually settles quickly"],
    benefits: ["Removes hardened deposits that brushing cannot remove", "Supports healthier gums and fresher breath", "Provides personalised guidance for difficult-to-clean areas"],
    appointment: "The gums and deposits are assessed before scaling instruments are used to clean around the teeth and gumline. Polishing is added where appropriate.",
    recovery: "Gums may feel mildly tender and teeth may be temporarily sensitive, particularly after heavier buildup is removed. This commonly improves within a short time.",
    maintenance: "The most suitable cleaning interval depends on gum health, deposit buildup, home care and individual risk rather than one schedule for everyone.",
  },
  {
    slug: "professional-whitening",
    title: "Professional Whitening",
    image: "/img/service-professional-whitening.jpg",
    summary: "Whitening planned around each patient’s needs and comfort.",
    overview: "Professional whitening is planned after checking dental health, existing restorations and sensitivity so expectations remain safe and realistic.",
    suitableFor: ["General tooth discolouration", "Stains from food or drinks", "Patients seeking a brighter smile"],
    process: ["Dental health and shade assessment", "Personalised whitening plan", "Progress review and sensitivity guidance"],
    aftercare: ["Follow the whitening instructions provided", "Reduce strongly coloured food and drinks after treatment"],
    benefits: ["Treatment strength and timing are professionally supervised", "Planning takes sensitivity and existing restorations into account", "Progress is measured against an initial tooth shade"],
    appointment: "Dental health is checked first. The whitening method, expected shade change and sensitivity plan are then selected for the individual patient.",
    recovery: "Temporary tooth sensitivity or gum irritation may occur. It usually settles, and the plan can be adjusted if sensitivity becomes uncomfortable.",
    maintenance: "Whitening is not permanent. Diet, smoking, oral hygiene and natural ageing affect how long brightness lasts, and occasional maintenance may be advised.",
  },
  {
    slug: "cleaning-and-whitening",
    title: "Cleaning & Whitening",
    image: "/img/service-cleaning-whitening.jpg",
    summary: "A combined appointment for professional cleaning and teeth whitening.",
    overview: "A combined plan begins by removing deposits and surface stains, then considers whitening to improve overall brightness in a coordinated way.",
    suitableFor: ["Surface staining with calculus buildup", "Patients preparing for an event", "A comprehensive smile refresh"],
    process: ["Dental and gum assessment", "Professional cleaning and polishing", "Whitening planned around comfort and dental health"],
    aftercare: ["Maintain careful oral hygiene", "Follow dietary and sensitivity advice after whitening"],
    benefits: ["Removes deposits before tooth colour is reassessed", "Coordinates stain removal and whitening in one plan", "Creates a cleaner baseline for a more predictable discussion"],
    appointment: "The visit begins with a dental and gum check followed by scaling and polishing. Whitening is provided or planned only when the mouth is suitable.",
    recovery: "The gums can feel tender after cleaning and the teeth may be temporarily sensitive after whitening. Individual advice is provided for both.",
    maintenance: "Daily plaque control and sensible stain habits help preserve the result. Future cleaning or whitening maintenance is based on clinical need.",
  },
  {
    slug: "smile-brightening-care",
    title: "Smile Brightening Care",
    image: "/img/service-smile-brightening.jpg",
    summary: "Personalised cleaning and whitening guidance with attention to detail.",
    overview: "Smile brightening care combines assessment, stain management and individual guidance to help improve brightness without overlooking dental health.",
    suitableFor: ["A dull-looking smile", "Recurring surface stains", "Patients unsure which brightening option suits them"],
    process: ["Assessment of stains and existing restorations", "Cleaning or whitening recommendations", "A maintenance plan suited to daily habits"],
    aftercare: ["Use recommended oral-care products", "Arrange maintenance according to your individual plan"],
    benefits: ["Separates removable surface stain from deeper tooth colour", "Avoids unsuitable one-size-fits-all brightening choices", "Builds a realistic plan around health and daily habits"],
    appointment: "The source of discolouration, gum condition and existing fillings or crowns are reviewed. Suitable cleaning, whitening or restorative options are then explained.",
    recovery: "Recovery depends on the care selected. Cleaning usually has minimal downtime, while whitening can cause temporary sensitivity that should be monitored.",
    maintenance: "A tailored routine may include hygiene visits, stain reduction and occasional whitening maintenance. Existing crowns and fillings do not whiten like natural teeth.",
  },
  {
    slug: "zirconia-crowns",
    title: "Zirconia Crowns",
    image: "/img/service-zirconia-crowns.jpg",
    summary: "Natural-looking zirconia crowns within carefully planned restorative care.",
    overview: "Zirconia crowns can restore strength, form and appearance when a tooth needs broader coverage, with planning focused on fit, bite and natural aesthetics.",
    suitableFor: ["Heavily restored or weakened teeth", "Fractured teeth", "Teeth requiring full-coverage restoration"],
    process: ["Clinical and radiographic assessment", "Tooth preparation and precise records", "Try-in, bite review and final placement"],
    aftercare: ["Clean carefully around the crown and gumline", "Attend reviews to monitor the crown and supporting tooth"],
    benefits: ["Provides full coverage for a structurally compromised tooth", "Combines strength with carefully planned tooth-like form", "Restores bite contact and helps protect remaining tooth tissue"],
    appointment: "After assessment, the tooth is prepared and precise records are taken. A temporary crown may protect it while the zirconia crown is made before try-in and bonding.",
    recovery: "Mild gum tenderness or sensitivity can occur after preparation and placement. Contact the clinic if the bite feels high or discomfort does not improve.",
    maintenance: "A crown cannot decay, but the supporting tooth and gum still need daily cleaning. Longevity depends on fit, bite, hygiene and habits such as grinding.",
  },
  {
    slug: "full-mouth-rehabilitation",
    title: "Full-Mouth Rehabilitation",
    image: "/img/service-full-mouth-rehabilitation.jpg",
    summary: "Comprehensive planning using zirconia crowns while maintaining healthy gums.",
    overview: "Full-mouth rehabilitation coordinates the restoration of multiple teeth to improve function, comfort and appearance through careful staged planning.",
    suitableFor: ["Extensive tooth wear or damage", "Multiple failing restorations", "Complex functional and aesthetic concerns"],
    process: ["Comprehensive examination and records", "Phased treatment and outcome planning", "Restoration with ongoing bite and gum review"],
    aftercare: ["Commit to regular professional maintenance", "Use any recommended protective appliance"],
    benefits: ["Coordinates function, comfort and appearance across multiple teeth", "Breaks complex care into clear, manageable stages", "Allows bite and gum response to be reviewed throughout treatment"],
    appointment: "Comprehensive records may include photographs, scans, radiographs and bite analysis. Treatment is usually phased, with provisional stages used when clinically helpful.",
    recovery: "Recovery differs by stage and by the number of teeth treated. Temporary sensitivity, muscle awareness or an adjustment period may occur as the bite changes.",
    maintenance: "Long-term success relies on excellent home care, professional maintenance and protection from excessive bite forces. A night guard may be recommended.",
  },
  {
    slug: "restorative-smile-planning",
    title: "Restorative Smile Planning",
    image: "/img/service-restorative-planning.jpg",
    summary: "A structured assessment for multi-tooth restoration with zirconia crowns.",
    overview: "Restorative smile planning brings together dental health, facial proportions, tooth position and bite before treatment begins across several teeth.",
    suitableFor: ["Several teeth needing restoration", "Complex crown planning", "Patients considering a broader smile change"],
    process: ["Clinical examination, photographs and records", "Discussion of priorities and possible stages", "A clear personalised restorative plan"],
    aftercare: ["Follow the phased plan and review schedule", "Maintain gum health throughout treatment"],
    benefits: ["Clarifies priorities before irreversible treatment begins", "Connects tooth shape, facial proportions and bite", "Supports informed decisions about sequence, materials and timing"],
    appointment: "The planning visit gathers photographs, scans, radiographs and clinical findings as needed. Options, limitations, stages and maintenance responsibilities are then discussed.",
    recovery: "Planning itself requires no recovery. If trial shapes or temporary restorations are used, a short adjustment period may help assess comfort and appearance.",
    maintenance: "The written plan should be reviewed if dental health, priorities or circumstances change. Stable gum health remains important before and during restorative care.",
  },
  {
    slug: "crown-shape-and-shade-planning",
    title: "Crown Shape & Shade Planning",
    image: "/img/service-crown-shape-shade.jpg",
    summary: "Detail-oriented crown proportion and colour planning for a balanced smile.",
    overview: "Shape and shade planning considers tooth proportions, neighbouring teeth, facial features and light reflection before the final crown is completed.",
    suitableFor: ["Front-tooth crown treatment", "Matching a crown to natural teeth", "Refining symmetry and tooth proportions"],
    process: ["Photographic and shade assessment", "Proportion and contour discussion", "Try-in review before final approval"],
    aftercare: ["Maintain gentle cleaning at the crown margin", "Contact the clinic if the bite or appearance needs review"],
    benefits: ["Balances crown proportions with the face and neighbouring teeth", "Evaluates colour, brightness and translucency together", "Provides a try-in opportunity before final approval when possible"],
    appointment: "Photographs and shade information are recorded in suitable lighting. Shape, surface texture and tooth contacts are reviewed during try-in before final placement.",
    recovery: "There is usually no recovery from planning itself. After crown placement, mild temporary gum tenderness or awareness of the new shape may occur.",
    maintenance: "Good gum health helps the crown margin remain natural-looking. Regular reviews monitor the bite, supporting tooth, colour harmony and surrounding tissues.",
  },
];

export function getTreatment(slug: string) {
  return TREATMENTS.find((treatment) => treatment.slug === slug);
}